# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----separator

------separator
Content-Disposition: form-data; name="file"; filename="teste2.mp3"
Content-Type: audio/mpeg

< ./teste2.mp3
------separator--

###
# @name get-prompts
GET http://localhost:3333/prompts

###
# @name create-transcription
POST http://localhost:3333/videos/c33d5a80-5ddf-4e01-b837-53335ad89883/transcription
Content-Type: application/json

{
  "prompt": "gaara, demônionio , ninja"
}

###
# @name generate-ai-complete
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "fa101428-5982-414b-a803-b0143242bbc6",
  "temperature": 0.5,
  "prompt": "gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}
